### PR TITLE
FEAT: adding a setting to configure the landing space for the UI

### PR DESCRIPTION
**Pull request by hina-shah**
This PR is in conjunction with https://github.com/helxplatform/helx-ui/pull/286 to add config.default_space setting in the chart. This sets the landing space for the target website.

### CODE REVIEW

**Review by frostyfan109 — CHANGES_REQUESTED** [review]
Could you change the default to search instead? I'd rather not change the default behavior since most deployments will still want search as the landing anyways. Also, did you make sure that it works if you disable workspaces and set the landing to workspaces (and vice versa for search)?

**Comment by hina-shah** [comment]
> Could you change the default to search instead? I'd rather not change the default behavior since most deployments will still want search as the landing anyways. Also, did you make sure that it works if you disable workspaces and set the landing to workspaces (and vice versa for search)?

Changed default to search. Also did the same in the UI: https://github.com/helxplatform/helx-ui/pull/286/commits/efc4e653b98a250a7d66f396620d2796ac1cffac

**Comment by waTeim** [comment]
Hmm, I would have said the opposite; most deployments don't have search.  But after making a simple accounting, I'm thinking it's more like 50/50 in which case either is ok.  Maybe in the future, it might change, we can reaccess then.

**Review by waTeim — APPROVED** [review]

**Review by frostyfan109 — APPROVED** [review]

**Comment by hina-shah** [comment]
@frostyfan109 @waTeim : Just added a commit to "Deduce" the default landing space when only one of workspace or search is enabled.

**Comment by waTeim** [comment]
you also need to set the version in Chart.yaml; only the containers get their version automatically updated.

**Review by waTeim — APPROVED** [review]

**Pull request merged**
