### PR TITLE
This commit changes how the analytics value is structured to simplifiy

### PR DESCRIPTION
**Pull request by cschreep**
the process of passing env vars down the chain

### CODE REVIEW

**Comment by connectbo** [comment]
Not sure about this one.. I see `analytics.enabled` and `analytics.auth` are being used in Griffin's code, if we are passing a token as the whole analytics variable, that might throw error

**Comment by cschreep** [comment]
There is a corresponding change to the helx-ui so that only the token itself needs to be passed as a variable: https://github.com/helxplatform/ui-chart/pull/7

**Comment by connectbo** [comment]
ohh my bad, I didn't see that one. Looks good.

**Review by connectbo — APPROVED** [review]
ohh my bad, I didn't see that one. Looks good.

**Pull request merged**
