### PR TITLE
FEAT: Adding configurable options

### PR DESCRIPTION
**Pull request by hina-shah**
This PR is to support https://github.com/helxplatform/helx-ui/pull/297, which adds several configurable "branding" options for a helx deployment.

Following are added:
- environment variable values:
  - `config.login_title` :  This provides a custom heading displayed on the workspaces login page. Default value is empty. When empty, the login title becomes `<config.meta.title> Workspaces`.
  - `config.support.help_portal_url`: URL to a help portal/bug reporting/feature request page. Default is empty. When empty, the corresponding section does not show up on Support page.
  - `config.support.user_guide_url`: URL to a user guide for the deployment. This can potentially have a default url value, but we don't have an active link right now, so this is empty. When empty, it does not show up under `Documentation` section.
  - `config.support.faqs_url`: URL to a FAQs page for the deployment. This can also be potentially default, but we don't have an active page. When empty, the corresponding section does not show up under `Documentation`.
 - ConfigMap mounted login title description:
   -  adding a `Values.config.brand_description.html` value to helm chart, which will encode a multiline html describing the brand.`, this will be mounted to "/usr/share/nginx/static/frontend/brand_desc.html"` and read in by the helx-ui.

AND update README

### CODE REVIEW

**Comment by frostyfan109** [comment]
Need to bump the version

**Review by frostyfan109 — CHANGES_REQUESTED** [review]
~Version needs bump~ nevermind didn't notice it's a master release ignore this

**Comment by waTeim** [comment]
Can you change IfNotPresent to Always.

Also, does this require a change in version (in Chart.yaml) I note the comment above, but I assert, it still does because you're not going to mod develop directly, you're simply going to merge develop to master.

**Comment by hina-shah** [comment]
> Can you change IfNotPresent to Always.

I'm hesitant to do it in this PR, as it does not relate to the changes, and I don't know what consequences it will create.
> 
> Also, does this require a change in version (in Chart.yaml) I note the comment above, but I assert, it still does because you're not going to mod develop directly, you're simply going to merge develop to master. 

New PR coming up.

**Review by waTeim — APPROVED** [review]

**Pull request merged**
